total_user_income = float(input("Enter your total income this year: "))
owed_taxes = 0
new_user_income = 0
if total_user_income >= 609351:
    new_user_income = total_user_income - 609350
    owed_taxes+= new_user_income * 0.37
    total_user_income-= new_user_income
if total_user_income >= 243726:
    new_user_income = total_user_income - 243725
    owed_taxes+= new_user_income * 0.35
    total_user_income-= new_user_income
if total_user_income >= 191951:
    new_user_income = total_user_income - 191950
    owed_taxes+= new_user_income * 0.32
    total_user_income-= new_user_income
if total_user_income >= 100526:
    new_user_income = total_user_income - 100525
    owed_taxes+= new_user_income * 0.24
    total_user_income-= new_user_income
if total_user_income >= 47151:
    new_user_income = total_user_income - 47150
    owed_taxes+= new_user_income * 0.22
    total_user_income-= new_user_income
if total_user_income >= 11601:
    new_user_income = total_user_income - 11600
    owed_taxes+= new_user_income * 0.12
    total_user_income-= new_user_income
if total_user_income <= 11600:
    owed_taxes+= total_user_income * 0.1
print(f"You owe ${owed_taxes:.2f} this year.")